import random
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from datetime import datetime
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait

def test_avocado_o():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    coffee.click()
    black.click()
    driver.execute_script("window.scrollBy(0, 100);")
    salty.click()
    hot.click()
    fork.click()
    driver.execute_script("window.scrollBy(0, 100);")
    shallow.click()
    vegetables.click()
    beer.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Avocado Benedict"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_avocado_1():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    coffee.click()
    black.click()
    driver.execute_script("window.scrollBy(0, 100);")
    salty.click()
    hot.click()
    fork.click()
    driver.execute_script("window.scrollBy(0, 100);")
    shallow.click()
    vegetables.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Avocado Benedict"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_Strawberry_2():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    coffee.click()
    black.click()
    driver.execute_script("window.scrollBy(0, 100);")
    salty.click()
    hot.click()
    fork.click()
    driver.execute_script("window.scrollBy(0, 100);")
    shallow.click()
    fruit.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Strawberry Sundae"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_Strawberry_3():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    coffee.click()
    black.click()
    driver.execute_script("window.scrollBy(0, 100);")
    salty.click()
    hot.click()
    fork.click()
    driver.execute_script("window.scrollBy(0, 100);")
    deep.click()
    fruit.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Strawberry Sundae"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_Soy_4():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    coffee.click()
    black.click()
    driver.execute_script("window.scrollBy(0, 100);")
    salty.click()
    hot.click()
    spoon.click()
    driver.execute_script("window.scrollBy(0, 100);")
    deep.click()
    fruit.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Soy Salmon"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_Soy_5():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    coffee.click()
    black.click()
    driver.execute_script("window.scrollBy(0, 100);")
    salty.click()
    sour.click()
    spoon.click()
    driver.execute_script("window.scrollBy(0, 100);")
    deep.click()
    fruit.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Soy Salmon"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_Culiflower_6():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    coffee.click()
    black.click()
    driver.execute_script("window.scrollBy(0, 100);")
    sweet.click()
    sour.click()
    spoon.click()
    driver.execute_script("window.scrollBy(0, 100);")
    deep.click()
    fruit.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Culiflower Dipper"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_Culiflower_7():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    coffee.click()
    white.click()
    driver.execute_script("window.scrollBy(0, 100);")
    sweet.click()
    sour.click()
    spoon.click()
    driver.execute_script("window.scrollBy(0, 100);")
    deep.click()
    fruit.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Culiflower Dipper"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_Blonde_8():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    winter.click()
    tea.click()
    white.click()
    driver.execute_script("window.scrollBy(0, 100);")
    sweet.click()
    sour.click()
    spoon.click()
    driver.execute_script("window.scrollBy(0, 100);")
    deep.click()
    fruit.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Blonde"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult

def test_Blonde_8():
    options = webdriver.ChromeOptions()
    options.add_argument("-incognito")
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('http://10.15.1.204:3000/')
    driver.maximize_window()
    problem2 = driver.find_element(By.CSS_SELECTOR, "#ftco-nav > ul > li:nth-child(3) > a")
    problem2.click()
    summer = driver.find_element(By.ID, "btn1")
    winter = driver.find_element(By.ID, "btn2")
    tea = driver.find_element(By.ID, "btn3")
    coffee = driver.find_element(By.ID, "btn4")
    white = driver.find_element(By.ID, "btn5")
    black = driver.find_element(By.ID, "btn6")
    sweet = driver.find_element(By.ID, "btn7")
    salty = driver.find_element(By.ID, "btn8")
    sour = driver.find_element(By.ID, "btn9")
    hot = driver.find_element(By.ID, "btn10")
    spoon = driver.find_element(By.ID, "btn11")
    fork = driver.find_element(By.ID, "btn12")
    deep = driver.find_element(By.ID, "btn13")
    shallow = driver.find_element(By.ID, "btn14")
    fruit = driver.find_element(By.ID, "btn15")
    vegetables = driver.find_element(By.ID, "btn16")
    cocktail = driver.find_element(By.ID, "btn17")
    beer = driver.find_element(By.ID, "btn18")
    readMyMind = driver.find_element(By.ID, "readmymind")

    summer.click()
    tea.click()
    white.click()
    driver.execute_script("window.scrollBy(0, 100);")
    sweet.click()
    sour.click()
    spoon.click()
    driver.execute_script("window.scrollBy(0, 100);")
    deep.click()
    fruit.click()
    cocktail.click()
    driver.execute_script("window.scrollBy(0, 100);")
    readMyMind.click()
    expectedResult = "Blonde"
    recommendation = driver.find_element(By.ID, 'recHeader')
    assert recommendation.text == expectedResult
